### ISSUE TITLE
Publish it on bower

### ISSUE THREAD

**Issue by roccomuso** [feross/p2p-graph#2]
It's a front-end lib, it's worth having it also on `bower`.

**Comment by feross** [comment]
I think bower has been deprecated for a while, in favor of npm. Even bower team members are recommending that people use npm going forward.

That said, if you want to publish to bower, go for it. Is there a way to publish without adding a `bower.json`, since that file always gets out of date with `package.json` and it's a maintenance burden.

**Comment by roccomuso** [comment]
@feross You're right. Let's avoid bower and keep it clean then.
