### ISSUE TITLE
Vue.js

### ISSUE THREAD

**Issue by jhemmmm** [feross/p2p-graph#24]
Hello,

I can't seem to be able to use this on my Laravel Project which use Vue.js

I'm getting something
`S - Error in mounted hook: “TypeError: self_data" or something`

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
